blueprint:
  domain: script
  name: Notify user
  description: >-
    Notify a user
  input:
    notify_device:
      name: "Device to notify"
      selector:
        entity:
          integration: notify
      default: []

mode: parallel

variables:
  device: !input notify_device
  data: "{{ {} }}"

sequence:
  - alias: "Send notification"
    service: "{{ device }}"
    data: >-
     {{ data if defined else {} }}